import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const COURSE_CONTENTS: Record<string, string> = {
  // FIRST Professional
  "PHT-301": "Introduction to Pharmacy and History: orientation with latest applications, survey from ancient Greek/Arab periods, contribution of Muslim scientists, Industrial Revolution, 20th and 21st century developments (Biotechnology, Nanotechnology, AI). Pharmaceutical Literature: scientific literature types, official texts and compendia. Physico-Chemical Principles: solutions, solubility, solubilization, dissolution, permeation, polymorphism. Ionization and Buffers. Micromeritics: particle size distribution, morphological characteristics, methods of analysis, flow properties.",
  "PHT-303": "Concepts of Physicochemical Principles. Preparation of Solutions, Dilutions, and Standard Curve. Concentration expressions (Molarity, Normality, Percentage). Solubility determination techniques. Buffer solutions and pH meter calibration. Characterization of powders (particle size, Carr’s Index, Hausner’s ratio, angle of repose).",
  "PHC-305": "Basic concepts: Chemical Bonding, Hybridization, Resonance, Hyperconjugation, Aromaticity, Electronegativity, Dipole Moment, Tautomerism. Synthesis, structure, and applications of alkanes, alkenes, alkynes, phenols, ethers, amines, ketones, aldehydes, carboxylic acids, esters, amides, and aromatic compounds. Organic Reactions Mechanism: Oxidation, Reduction, Substitution (SN1, SN2), Elimination, Addition, Rearrangement. Stereochemistry: Optical Isomerism, Chirality, Geometrical Isomerism (cis/trans, E/Z), Fischer and Sawhorse Projections.",
  "PHC-307": "Good laboratory practice, handling of materials, introduction to lab apparatus. Functional group identification (carboxylic acids, phenol, aldehydes, ketones, amines, nitro group, alcohol). Synthesis of derivatives (esters, amides, salts, etc.). Determination of melting and boiling points. Purification via recrystallization. Identification of various organic compounds.",
  "PHC-309": "General introduction to Pharmaceutical Biochemistry. Biochemistry of Carbohydrates: classification, isomerism, metabolism (glycolysis, pentose phosphate pathway, citric acid cycle), metabolic disorders. Bioenergetics: Electron transport chain, oxidative phosphorylation, reactive oxygen species. Biochemistry of Lipids: classification, digestion, absorption, metabolism (beta-oxidation, biosynthesis), metabolic disorders. Biochemistry of Vitamins: classification, structures, metabolic functions, deficiencies. Biochemistry of Hormones: classification, pharmaceutical importance.",
  "PHC-311": "General introduction. Qualitative and Quantitative analysis of Carbohydrates (monosaccharides, disaccharides, reducing sugars) using common tests (Molisch, Benedict, Fehling, etc.). Analysis of lipids and Sterols (Cholesterol), Bile salts, Bilirubin. Analysis of Glucose, Cholesterol, and Creatinine in Blood.",
  "PHL-313": "Basic Cell Functions: structure, fluid balance, cell cycle, apoptosis, transport mechanisms. Muscle Physiology: skeletal muscle fibers, contraction mechanisms, neuromuscular junction. Circulation: blood vessels, blood pressure regulation, arterial pressure, baroreceptor reflex, renin-angiotensin system. The Heart: anatomy, cardiac cycle, conduction system, ECG patterns, clinical significance. The Blood Cells: erythropoiesis, hemoglobin, white blood cells, types of T-cells, B-cells, platelets, blood coagulation, blood types. Digestion and Absorption of Food. Temperature Regulation and pathophysiology of fever.",
  "PHL-315": "Measurement of blood pressure and heart rate. Venous blood sampling and injection techniques. Body mass index (BMI) calculation. Peristaltic activity in rabbit jejunum. Visual acuity and field of vision. Abnormal ECG pattern identification. Effects of isotonic/hypotonic solutions on red blood cells.",
  "PHG-317": "Reading and Writing Skills: previewing, scanning essays, informational texts, process model for writing (prompts, proposals), CV and job application letters. Oral Interaction Skills: articulation, English accent, informational speeches, academic presentations, group discussions, decision-making templates. Vocabulary Skills: prefixes, suffixes, roots, derivation, academic word list. Grammar Skills: identifying grammatical terms, simple sentence types, tenses (past, present, future).",
  "PHT-302": "Surface and Interfacial Phenomena: surface tension, surfactants, micellization. Adsorption mechanisms and isotherms. Disperse Systems: Colloids, Emulsions (theories of emulsification), Suspensions (suspending agents, stability). Rheology: fluid flow behaviors, Newtonian/non-Newtonian liquids, thixotropy, rheopexy. Stability Studies in Pharmacy. Unit Operations: Precipitation, crystallization, evaporation, distillation, lyophilization, centrifugation, trituration, dialysis.",
  "PHT-304": "Chemical Kinetics: effect of temperature on stability, reaction rate constants, expiry date determination. Interfacial Phenomena: Critical Micelle Concentration (CMC) determination, flocculation volume analysis. Rheology: viscosity determination, rheogram plotting, stability of suspensions.",
  "PHC-306": "Heterocyclic Chemistry: medicinally important compounds (pyrrole, furan, thiophene, pyridine, pyrimidine, pyrazine, indole, quinoline), imidazole, purine/pyrimidine bases. Reaction Mechanisms and Intermediates: Carbocations, Carbanions, Carbenes, Nitrenes, Benzynes, Free Radicals. Named reactions (Baeyer-Villiger, Diels Alder, Grignard, Friedel Craft, Perkin, etc.). Advanced Organic Chemistry: Total Synthesis, Semi Synthesis, Green Chemistry.",
  "PHC-308": "Identification of organic compounds (Oxalic acid, salicylic acid, etc.). Synthesis of salicylic acid, Nifedipine, paracetamol, etc. Green Metallurgy methodology. Synthesis of Aspirin, Acetanilide, Iodoform. Elimination and Substitution reactions.",
  "PHC-310": "Proteins and Amino acids: classification, digestion, absorption, metabolism, urea cycle, biosynthesis of heme. Biochemistry of Nucleic Acids: bases, gene therapy, diagnostics, vaccines, nanotechnology. Biochemistry of Enzymes: classification, inhibition, activation, drug-enzyme interactions. Secondary Messengers: cAMP, Calcium ions. Clinical Biochemistry: lab tests for diagnosis (uric acid, cholesterol, etc.).",
  "PHC-312": "Analysis of Proteins (Biuret/Ninhydrin). Analysis of normal and abnormal Urine components. Estimation of Blood Urea Nitrogen, Serum Bilirubin, Calcium, Uric Acid, etc. Liver and Kidney Function Tests.",
  "PHL-314": "Thoracic region: skeletal, respiratory, and cardiovascular structures. Abdominal organs and related systems. Urinary system, limbs, and nervous system (spinal cord, brain, cranial nerves). Histological techniques and pharmacological relevance.",
  "PHL-316": "Anatomoical study of thoracic and abdominal organs using models. Urinary and reproductive system anatomy. Upper and lower limb bone/joint analysis. Brain/spinal cord structure identification. Tissue Fixation and micro-anatomy.",
  "PHL-318": "Nervous system control: neurons, action potentials, synapse function, neurotransmitters, central and autonomic systems. Respiratory system: gas exchange, lung volumes/capacities. Kidney function: urine formation, fluid/electrolyte balance. Reproductive systems: gamete formation, menstrual cycle.",
  "PHL-320": "Hematological tests: hemoglobin, ESR, RBC counting, coagulation time. AB0/Rh blood grouping. Respiratory parameters: tidal volume, inspiratory reserve, pulmonary function. Nebulization techniques and CPR. Vector control strategies. Heart/lung sound identification.",
  "PHL-322": "Need for religion and role of Wahi. Islamic concept of life and Universe. Islamic Beliefs (Aqaid): Tawhid, angels, prophethood, revealed books, Hereafter. Worship practices (Ibadat): Salat, Zakat, Sawm, Hajj. Ideology of Pakistan: historical movements, Constitution of 1973. Islamic moral values.",

  // SECOND Professional
  "PHT-401": "Purpose of dosage forms, pre-formulation studies, Solid Dosage Forms (Powders, Tablets, Capsules), Basic Principles of Compounding, Pharmaceutical Incompatibilities.",
  "PHT-403": "General introduction, functional anatomy of bacteria, microbial techniques, environmental microbiology, human-microbiome interactions, diseases caused by microorganisms.",
  "PHC-405": "Surface and Interfacial Phenomena, Adsorption, Disperse Systems (Colloids, Emulsions, Suspensions), Rheology, Stability studies.",
  "PHL-407": "Experiments on Blood Pressure, Heart Rate measurement. Body Mass Index (BMI). ECG patterns. Peristaltic activity. Visual acuity.",
  "PHL-410": "Pharmacology of drugs acting on Autonomic Nervous System, Cardiovascular System, Renal system.",
  "PHG-412": "Introduction to Pharmacognosy, Historical development, Scope. Quality control of crude drugs. General methods of extraction and isolation.",

  // THIRD Professional
  "PHT-502": "Experiments to demonstrate some of physico-chemical processes, like simple distillation, steam distillation, crystallization, Dialysis. Determination of emulsion systems. Practicals based on rheological and structural character of emulsions stabilized by mixed films of emulsifier. Determination of particle size, angle of repose of powders. Preparation of buffer solutions and isotonic solution. Determination of percentage composition of solutions by specific gravity method. Partition-coefficient, surface tensions, viscosity. Determination of various pH by acidic and alkaline buffers. Drug stability experiments, preparation of stock solution (dilution method). Determination of critical micelle concentration (CMC) of surface-active agents. Flocculation and deflocculation of Kaolin Suspensions.",
  "PHT-504": "Mixing Fundamentals, mechanism. Mixing equipment used in liquid/liquid, liquid/solid and solid/solid mixing. Comminution (size reduction), Reasons for size reduction. Factors affecting size reduction, size analysis. Sieving, energy mills (Ball mill, edrunner, edge runner mill disintegrant, colloid mill, hammer mill, cutter mill, fluid energy mill etc.).",
  
  // FOURTH Professional
  "PHP-601": "Hospital and Its Organization: Brief history of hospital, Classification of hospitals, Minimum requirements for registering a hospitals, Organizational structure, Administration, Clinical departments, Nursing, dietetic, pathology, blood bank, radiology and other supportive services, Hospital finances. Role of Pharmacy in Hospitals, Role of Pharmacist in Small Hospitals, Nursing Homes etc. Minimum Standards for Hospital Pharmacies as per ASHP: Pharmacy, its organization and personnel, The Physical plant and its equipment, Pharmacy specialist, Drug information centre, Poison control centre and antidote bank, Pharmacy education, CEs and CMEs, internship program, clerkship, etc. Professional services rendered, The Pharmacy: central sterile supply room (eye drops, ear drops) and hyper alimentation. Nuclear pharmacy, Investigational use of drugs, Health accessories, ancillary supplies and surgical supplies. Dispensing to Inpatients: Methods of dispensing and SOP’s, Unit dose dispensing, Other concepts of dispensing, satellite pharmacy etc. 200 Contact Hours Hospital Pharmacy Internship in a Tertiary Care General Hospital Covering the Clinical Units.",
  "PHT-606": "Compartment Models: One compartment model. Two compartment models. Three compartment models. Non-compartmental models. Biological Half-life in Vitamin. Clearance, Elevation. Protein Bounding. Multiple dosage. Application of Pharmacokinetics in Clinical Situation. Application in Dosage Sites. Bioavailability and bioequivalence testing. Pharmacokinetics of intravenous infusion.",
  "PHT-613": "Barriers to Drug Delivery Systems (DDS): Oral, IV, IM, Rectal, Pulmonary DDS. Reticulo-endothelial system. Principles of Non-Targeting/Conventional Pharmaceutical Formulations and Dosage Form Design: Need, product formulation and preformulation studies. Formulation development of Aerosols, Opthalmic and Parentral Preparations. Formulation development of Osmotic, Sustained-Release, Rapidly Disintegrating, Gastro-retentive drug delivery systems. Concept of Targeting DDS: Active vs. Passive Targeting. Targeting Strategies (Environment and stimuli sensitive targeting: pH, temperature, ions, photo, magnetic, ultrasound, etc. Regulated systems: enzyme complex etc. Ligand based targeting: Polymeric conjugates, biomacromolecular conjugates like antibody, affibody, aptamer and peptides etc.). Introduction and Types of Various Dosage Forms and DDS: Nanoparticles, nanospheres, dendrimers, nanohydrogels, liposomes, niosomes, gold and iron oxide nanoparticles. Brief over view of theragnostic systems. Principles of Formulation of Novel Drug Delivery Systems: Introduction and brief overview of biomedical polymers, their physical and structure-property relationship. Examples of bio-responsive and stimuli responsive polymers. Overview of methods to formulate polymeric nanoparticles, dendrimers, liposomes, niosomes, hydrogels and gold nanoparticles etc. Selection of ligands for delivery system with examples to targeting substrates. Formulation stability issues associated with novel DDS. Characterization Techniques for Novel DDS: Spectrophotometric (FT-IR, HPLC, UV, Fluorescence-spectroscopy, NMR etc.). Particles size characterization (SEM, TEM, DLS, Size-exclusion chromatography etc.). Crystalline Structure (XRD etc.). Miscellaneous techniques (AFM, Raman-spectroscopy etc.). Pharmacokinetic and Pharmacological Aspects of Novel DDS: Clearance and in-vivo stability of novel DDS. Concept and strategies of designing long-circulating DDS. Drug and Disease Candidates for Novel DDS: Principles of selection of a disease. Principles of selection of drug(s) candidates for a disease.",
  "PHT-614": "To prepare matrix tablet of drugs by single-punch machine. Preparation of matrix tablet for less water-soluble drug. Preparation of matrix tablet for highly water-soluble drug. Perform dissolution testing by USP method I and II. Formulation of 2 Model Drugs (highly soluble and less soluble) in Nano particles/Micro particles. To prepare polymeric Nano/Micro particles by single / double emulsion / nanoprecipitation method(s). Hydrophilic drugs by double emulsion method. Hydrophobic drugs by single emulsion method. Hydrophobic drugs by nanoprecipitation method. To visualize the nano/microparticles under stereromicroscope. To perform the release testing of 2 model drugs from nanoparticles stirring method (UV-visible spectroscopy). To prepare the oral formulation of drugs by extrusion/spheronization method. Matrix based pellets. Coated pellets (perform coating). Pellitization to form immediate release, controlled/extended release and enteric coated pellets.",

  // FIFTH Professional
  "PHC-707": "Assay of pharmaceutical compounds based on spectrophotometric methods. Separation, identification and quantitation of a drug substance by chromatographic methods such as TLC, GLC, HPLC. To study the methods development procedure of a drug substance by UV-Visible spectroscopy/TLC/GLC/HPLC. To study the experimental methodology of validation of a drug substance by UV-Visible spectroscopy/TLC/GLC/HPLC.",
  "PHC-709": "To study the chemistry, structure, mechanism of action, structure activity relationship and therapeutic applications of the following: Analgesic and Antipyretics: Paracetamol, salicylic acid analogues, quinolines derivatives pyrazalone and pyrazolidines, N-aryl anthranilic acids, aryl and heteroaryl acetic acid derivatives. Local Anesthetics: Benzoic acid derivatives, lidocaine derivatives (anilids), amino benzoic acid, miscellaneous compounds such as: Procaine, lignocaine, eucaine, cocaine and benzocaine.",
  "PHP-714": "Pharmacotherapy of Drugs Used in: CVS Unit (covering IHD, hypertension etc.). Pulmonary Unit (asthma, COPD, pneumonia etc.). Infection Unit (bacterial, fungal and viral infections). Endocrinology Unit (DM, hyper / hypothyroidism etc.). Nephrology Unit (renal failures etc.). Hematology Unit (bleeding disorders, coagulopathies). Manufacturing Bulk and Sterile: Total parenteral nutrition (TPN)."
};

async function main() {
  console.log('--- Updating Course Contents ---');
  
  for (const [code, contents] of Object.entries(COURSE_CONTENTS)) {
    const updated = await prisma.course.updateMany({
      where: { code },
      data: { contents }
    });
    
    if (updated.count > 0) {
      console.log(`Updated contents for: ${code}`);
    } else {
      console.log(`Course not found: ${code}`);
    }
  }
  
  console.log('--- Update Completed ---');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
